# -*- coding: utf-8 -*-
"""ZomatoDataAnalytics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1whueLswF1m8cafTMDHzTZN1m_d_r8j6Z
"""

#Importing Liabries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# importing data

df = pd.read_csv('/content/Zomato data .csv')

df

# convert the datatype of of column - rate

'''def handle_rate(value):
  value = str(value).split('/')
  value = value[0]
  return float(value)

df['rate'] = df['rate'].apply(handle_rate)'''

# Remove '/5' from the rate column
df['rate'] = df['rate'].str.replace('/5', '', regex=True)

# Convert the column to float
df['rate'] = pd.to_numeric(df['rate'], errors='coerce')

df['rate']

df.head()

# to check null values in any features
df.info()

## Type of Resturent
df.head()

sns.countplot(x=df['listed_in(type)'])
plt.xlabel('Resturent')
plt.ylabel('Count')
plt.title('Type of Resturent')
plt.show()

# conclusion : majority of resturent falls in dining category

df.head()

# to know how many votes each type of resturent received from customers

grouped_data= df.groupby('listed_in(type)')['votes'].sum()
result = pd.DataFrame({'votes':grouped_data})
plt.plot(result,c='red',marker='o')
plt.xlabel('Resturent',c= 'red',size=15)
plt.ylabel('Count',c= 'red',size=15)
plt.title('Type of Resturent')
plt.show()

# conclusion : dining resturent has received maximum votes , buffet and cafes need some improvement

df.head()

plt.hist(df['rate'],bins=5)
plt.xlabel('Rate')
plt.ylabel('Count')
plt.title('Distribution of Rate')
plt.show()

# conclusion : majority of resturent received rating from 3.5 to 4

# Average order spending by couples

df.head()

# average spending by couple

couple_data = df['approx_cost(for two people)']
sns.countplot(x=couple_data)
plt.xlabel('Average order spending by couples')
plt.ylabel('Count')
plt.title('Average order spending by couples')
plt.show()

# conclusion : the majority of couples prefer resturents with an approximate order value of rs300

# which mode receive maximum rating ?
df.head()

plt.figure(figsize =(6,6))
sns.boxplot(x= 'online_order',y='rate',data=df)
plt.show()

#conclusion : offline order received lower rating in comparison to online order

pivot_table = df.pivot_table(index='listed_in(type)',columns='online_order',aggfunc='size',fill_value=0)
sns.heatmap(pivot_table,annot=True,cmap='YlGnBu',fmt ='d')
plt.title('Resturent Type vs Online Order')
plt.xlabel('Online Order')
plt.ylabel('Resturent Type')
plt.show()

# Conclusion : Dinning resturent primarily accept offline orders, whereas cafes primarily receive online orders .
# This suggests that clients prefer to dine in resturents whereas online ordering is prefer in cafes.

